#!/bin/sh

appendpath() {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}
appendpath "$HOME/bin"
appendpath "$HOME/.local/bin"
appendpath "$HOME/scripts"

export EDITOR="nvim"
export PAGER="bat --plain --paging=always"
export OPENER="mimeo"
export BAT_THEME="base16"
export IPYTHONDIR="$HOME/.config/ipython"
export GOOGLE_API_KEY="no"
export GOOGLE_DEFAULT_CLIENT_ID="no"
export GOOGLE_DEFAULT_CLIENT_SECRET="no"
export OPENAI_API_KEY="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"
