#!/bin/sh

appendpath () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}
appendpath "$HOME/bin"

export EDITOR="nvim"
export BAT_THEME="base16"
