#!/bin/sh
# shellcheck disable=2034
Selection=false # emptty does not ask for desktop selection

# SOURCE
. /etc/profile
# shellcheck disable=1090
[ -f ~/.profile ] && . ~/.profile
[ -f ~/.config/Xresources ] && xrdb -I"$HOME"/.cache -merge ~/.config/Xresources

# X SETTINGS
autorandr -c
xset r rate 400 60 &
xbanish &

paint & # INIT WALLPAPER AND COLORS

# DAEMONS
killall pipewire 2> /dev/null; pipewire &
killall picom 2> /dev/null; picom -b

# programs below require pipewire to be initialized and running
# this is a hacky fix... using "until pidof" loop did not work
sleep 2
killall pulse_daemon.sh 2> /dev/null; ~/suckless/dwmblocks/daemons/pulse_daemon.sh &
killall dwmblocks 2> /dev/null; dwmblocks &

exec dbus-launch --exit-with-session /usr/local/bin/dwm
