#!/bin/sh

# WALLPAPER CACHE
WALLPAPER_DIR="$HOME/pics/wallpapers"
WALLPAPER_CACHE="$HOME/.cache/wallpaper"

COLORSCHEME=0
FAIL=0

# WRAP WALLUST
# DEFAULT TO PREVIOUS WALLPAPER IN CACHE IF NO ARGUMENTS,
# ELSE PASS ALL ARGUMENTS TO WALLUST
if [ -z "$*" ]; then
    # PICK BEST FIT COLORSCHEME IF COLORS COULD NOT BE GENERATED
    [ -f "$WALLPAPER_CACHE" ] && WALLPAPER="$(cat ~/.cache/wallpaper)"
else
    for arg in "$@"; do
        if [ -f "$arg" ]; then
            WALLPAPER="$arg"
            readlink -f "$WALLPAPER" > "$WALLPAPER_CACHE"
        elif [ "$arg" = "-r" ] || [ "$arg" = "--random" ]; then
            WALLPAPER="$WALLPAPER_DIR/$(ls "$WALLPAPER_DIR" | shuf -n 1)"
            readlink -f "$WALLPAPER" > "$WALLPAPER_CACHE"
        elif [ "$arg" = "-c" ] || [ "$arg" = "--colorscheme" ]; then
            COLORSCHEME=1
            [ -f "$WALLPAPER_CACHE" ] && WALLPAPER="$(cat ~/.cache/wallpaper)"
        fi
    done
fi

if [ "$COLORSCHEME" = 0 ]; then
    wallust $WALLPAPER 2> /dev/null || FAIL=1
fi

if [ "$FAIL" = 1 ] || [ "$COLORSCHEME" = 1 ]; then
    printf "####\nCOLORS NOT GENERATED, THEME IS BEING USED.\n####\n"
    THEME=$("$(dirname "$0")"/wal-theme-picker.py -c 4 "$WALLPAPER" |
        awk 'NR==2{print $2}' |
        shuf -n 1)
    wallust theme "$THEME"
fi

# SET WALLPAPER
killall xwallpaper 2> /dev/null; xwallpaper --daemon --zoom "$WALLPAPER"


# RELOAD HOOKS,
# ARE ALWAYS RUN
printf "===\nRELOADING SOFTWARE...\n===\n"

# XRESOURCES
xrdb -I"$HOME"/.cache -merge ~/.config/Xresources &&
    printf "\tXRESOURCES RELOADED.\n---\n"

# DWM
xsetroot -name "fsignal:1" &&
    printf "\tDWM RELOADED.\n---\n"

# DUNST
killall dunst; dunst 2> /dev/null & # could not find better solution
printf "\tDUNST RESTARTED.\n---\n"

# QUTEBROWSER
pgrep qutebrowser > /dev/null 2>&1 &&
    qutebrowser ":config-source" > /dev/null 2>&1 &&
    printf "\tQUTEBROWSER RELOADED.\n---\n"

# NVIM
for INSTANCE in $(nvr --nostart --serverlist); do
    nvr --nostart --servername "$INSTANCE" -c 'colorscheme base16' &&
        printf "\tRELOADED NVIM INSTANCE.\n"
done
printf "\tRELOADED ALL NVIM INSTANCES.\n---\n"

# SIOYEK
pgrep sioyek > /dev/null 2>&1 &&
    sioyek --execute-command source_config --execute-command-data "$HOME/.config/sioyek/colors.config" > /dev/null 2>&1 &&
    printf "\tSIOYEK RELOADED.\n---\n"
