#!/bin/sh

check(){
    if ! command -v "$1" > /dev/null 2>&1;then
        echo "please install $1"
        exit 1
    fi
}

git_clone(){
    if ping -c 1 github.com > /dev/null 2>&1; then
        git clone https://github.com/ar-bebop/dots.git 2> /dev/null ||
            echo "already cloned repo\n"
    else
        echo "no internet connection"
        exit 1
    fi
}

check git
check stow

if [ "$(pwd)" = "$HOME" ]; then
    git_clone
    cd ./dots
    ./bootstrap.sh install && echo "done." || echo "\nplease resolve conflicts"
else
    echo "wrong path or no internet connection"
    exit 1
fi
